### ISSUE TITLE
[Question]: OceanBase K8S cluster setup

### ISSUE THREAD

**Issue by dimidevops** [oceanbase/ob-operator#159]
### Description

Hi,

I'm trying to setup OB cluster on OpenShift 4.14.6 hosted on AWS.

I've installed the operator via helm (oceanbase/ob-operator:2.1.1) with no issues but when I try to deploy a test cluster I keep getting "PodSchedule" errors on the initial bootstrap pod.

![image](https://github.com/oceanbase/ob-operator/assets/147745543/bd32d6d7-3a9b-4e6f-9abc-1786bd7e5daa)

The yml I'm trying with:

```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: seta-obcluster
  namespace: oceanbase-system
spec:
  clusterName: seta
  clusterId: 1
  userSecrets:
    root: root-password
    proxyro: proxyro-password
    monitor: monitor-password
    operator: operator-password
  topology:
    - zone: zone1
      replica: 1
      nodeSelector:
        kubernetes.io/hostname: ip-10-20-226-171.ec2.internal
  observer:
    image: 'oceanbase/oceanbase-cloud-native:4.2.1.1-101010012023111012'
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: efs
        size: 50Gi
      redoLogStorage:
        storageClass: efs
        size: 50Gi
      logStorage:
        storageClass: efs
        size: 20Gi
  monitor:
    image: 'oceanbase/obagent:4.2.1-100000092023101717'
    resource:
      cpu: 1
      memory: 1Gi
```

I'm trying to pin the pod to this worker node by using nodeSelector with kubernetes.io/hostname label, but it keeps saying "Insufficient memory" and as you can see the node has the available 11GB memory that is requested in the yml. Even when I don't specify the nodeSelector the same issue is present.

![image](https://github.com/oceanbase/ob-operator/assets/147745543/1b24558b-ddf2-48d8-b6f6-3ab9688b3add)

Am I doing something wrong or the nodes really cannot support the OB deployment or maybe this is some bug?

Also, I noticed that it refuses to be scheduled on nodes that are mixed as infra/worker.

Thank you.

**Comment by PowerfooI** [comment]
Thank you for your feedback, first. @dimidevops 

The situation is awkward for us, too. I guess the cloud provider give your worker node less than 15.24 GiB memory that it shows. 

K8s does not schedule the pod to infra node because the nodes have `node-role.kubernetes.io/infra` taint that common pods do not tolerate. Maybe you can attach taint toleration for pods in obcluster like following YAML, 

```yaml
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: seta-obcluster
  namespace: oceanbase-system
spec:
  clusterName: seta
  clusterId: 1
  userSecrets:
    root: root-password
    proxyro: proxyro-password
    monitor: monitor-password
    operator: operator-password
  topology:
    - zone: zone1
      replica: 1
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          operator: "Exists"
          effect: "NoSchedule"
  observer:
    image: 'oceanbase/oceanbase-cloud-native:4.2.1.1-101010012023111012'
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: efs
        size: 50Gi
      redoLogStorage:
        storageClass: efs
        size: 50Gi
      logStorage:
        storageClass: efs
        size: 20Gi
  monitor:
    image: 'oceanbase/obagent:4.2.1-100000092023101717'
    resource:
      cpu: 1
      memory: 1Gi
```

Let us know if this does not work.
