### ISSUE TITLE
[Feature]: Horizontal Cluster Autoscaler for OceanBase

### ISSUE THREAD

**Issue by PowerfooI** [oceanbase/ob-operator#172]
### Describe your use case

Configure a Horizontal Cluster Autoscaler to watch resource utilization of specific cluster or tenant. If the utilization rate keep high or low enough, the autoscaler scales up or down the cluster or tenant.

### Describe the solution you'd like

Maybe a new CRD named `HorizontalAutoscaler` could be create to handle such a use case. The draft spec can be like:

```yaml
spec:
    clusterName:
    tenantName: 
    targetCPUUtilization: 
    targetMemoryUtilization: 
    maxZones: 
    minZones:
    maxServers: 
    minServers:
    maxUnits: 
    minUnits:
    maxUnitConfig: 
    minUnitConfig:
```
