### ISSUE TITLE
[Feature]: support use default storageclass 

### ISSUE THREAD

**Issue by willzhang** [oceanbase/ob-operator#389]
### Describe your use case

I want to automate the entire installation process in multiple different environments, but the storageClass parameter must be set to a specific value, but the storageClass in different environments may have different default parameters.

![image](https://github.com/oceanbase/ob-operator/assets/33590311/1b443bb5-783b-4cd3-923b-2758cd44c527)

### Describe the solution you'd like

support none values for storageclass `""`
```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: test
  namespace: default
spec:
  clusterName: obcluster
  clusterId: 1
  serviceAccount: "default"
  userSecrets:
    root: root-password
  topology:
    - zone: zone1
      replica: 1
  observer:
    image: oceanbase/oceanbase-cloud-native:4.2.1.3-103000032023122818
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: ""
        size: 50Gi
      redoLogStorage:
        storageClass: ""
        size: 50Gi
      logStorage:
        storageClass: ""
        size: 20Gi
  parameters:
  - name: system_memory
    value: 1G
  - name: "__min_full_resource_pool_memory"
    value: "2147483648" # 2G
```

and let it use the default one.
```
root@node40:~# kubectl get sc
NAME                          PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
seaweedfs-storage (default)   seaweedfs-csi-driver   Delete          Immediate           true                   6h34m
```
