### ISSUE TITLE
How to integrate Custom StorageClass with OBCluster Deployment

### ISSUE THREAD

**Issue by qchenzi** [oceanbase/ob-operator#494]
### Description

Hello everybody,
     I am currently implementing the OceanBase database within a Kubernetes environment that employs a custom scheduler and StorageClass. Our deployment has specific requirements for PVC bindings, which are currently challenging to implement directly in the OBCluster configuration.

**Requirements**:

1. Pod Annotations: Our deployment strategy involves annotating pods with specific labels to meet the scheduling and storage policies. For example, in a typical StatefulSet, we can add the necessary annotations like this:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myobcluster
spec:
  template:
    metadata:
      annotations:
        volumeType: LocalStorage  # the necessary annotation
    spec:
      schedulerName: ${schedulerName} # the necessary schedulerName
```
However, I am unsure how to add similar annotations within an OBCluster deployment to ensure the pods meet our custom scheduler's requirements.

2. Volume Claim Templates: Our PVCs need to be annotated with specific labels and follow certain naming conventions to align with our storage infrastructure. Typically, this is handled as follows:

```yaml
volumeClaimTemplates:
  - metadata:
      name: data      # the certain name
      annotations:
        operator.datamars.org/diskType: local_ssd   # the necessary annotation
    spec:
      storageClassName: ${storageClassName}
      containers:
      ...
```
**Questions**:

- How can we configure pod annotations specifically for OBCluster pods?

- What is the recommended approach to set annotations and naming for volumeClaimTemplates in an OBCluster environment?

This customization is crucial for integrating OceanBase with our existing Kubernetes infrastructure, which has customize scheduling and storage mechanisms.

I would appreciate any documentation, examples, or guidance on how to achieve these configurations.

Thank you for your support and looking forward to your suggestions.

Best regards
