### ISSUE TITLE
[Bug]: <ERROR 2013 (HY000): Lost connection to MySQL server during query>

### ISSUE THREAD

**Issue by 66545shiwo** [oceanbase/ob-operator#57]
**Describe the bug**

Sometimes lost connection:

```
#  obclient -hhadoop002 -P30083 -uroot@sys oceanbase -A -c

obclient [oceanbase]> SET SESSION ob_query_timeout=200000000;
ERROR 2013 (HY000): Lost connection to MySQL server during query
obclient [oceanbase]> SET SESSION ob_query_timeout=200000000;
ERROR 2006 (HY000): OceanBase server has gone away
No connection. Trying to reconnect...
Connection id:    10
Current database: oceanbase

Query OK, 0 rows affected (0.063 sec)

obclient [oceanbase]> set global ob_query_timeout=200000000;
ERROR 2013 (HY000): Lost connection to MySQL server during query
obclient [oceanbase]> set global ob_query_timeout=200000000;
ERROR 2006 (HY000): OceanBase server has gone away
No connection. Trying to reconnect...
Connection id:    13
Current database: oceanbase

Query OK, 0 rows affected (0.294 sec)

obclient [oceanbase]> 

```
**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- Component Version:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obproxy
  namespace: obcluster
spec:
  selector:
    matchLabels:
      app: obproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: obproxy
    spec:
      containers:
        - name: obproxy
          image: xxxx:5000/oceanbasedev/obproxy-ce:4.1.0.0-7
          ports:
            - containerPort: 2883
              name: "sql"
            - containerPort: 2884
              name: "prometheus"
          env:
            - name: APP_NAME
              value: helloworld
            - name: OB_CLUSTER
              value: ob-test
            - name: RS_LIST
              value: $(SVC_OB_TEST_SERVICE_HOST):$(SVC_OB_TEST_SERVICE_PORT)
          resources:
            limits:
              memory: 16Gi
              cpu: "4"

```

```
apiVersion: cloud.oceanbase.com/v1
kind: OBCluster
metadata:
  name: ob-test
  namespace: obcluster
spec:
  imageRepo: hadoop002:5000/oceanbase-cloud-native
  tag: 4.1.0.0-100000192023032010
  imageObagent: hadoop002:5000/obagent:1.2.0
  clusterID: 1
  topology:
    - cluster: cn
      zone:
      - name: zone1
        region: region1
        nodeSelector:
          ob.zone: zone1
        replicas: 1
      - name: zone2
        region: region1
        nodeSelector:
          ob.zone: zone2
        replicas: 1
      - name: zone3
        region: region1
        nodeSelector:
          ob.zone: zone3
        replicas: 1
      parameters:
        - name: log_disk_size
          value: "180G"
  resources:
    cpu: 8
    memory: 64Gi
    storage:
      - name: data-file
        storageClassName: "local-path-hdd"
        size: 200Gi
      - name: data-log
        storageClassName: "local-path-hdd"
        size: 200Gi
      - name: log
        storageClassName: "local-path-hdd"
        size: 30Gi
      - name: obagent-conf-file
        storageClassName: "local-path-hdd"
        size: 1Gi
    #volume:
    #    name: backup
    #    nfs:
    #      server: ${nfs_server_address}
    #      path: /opt/nfs
    #      readOnly: false
```

```
apiVersion: v1
kind: Service
metadata:
  name: obproxy-service
  namespace: obcluster
spec:
  type: NodePort
  selector:
    app: obproxy
  ports:
    - name: "sql"
      port: 2883
      targetPort: 2883
      nodePort: 30083
    - name: "prometheus"
      port: 2884
      targetPort: 2884
      nodePort: 30084

```

k8s : v1.23.12
**Fast Reproduce Steps(Required)**

**Expected behavior**

**Actual Behavior**

**Additional context**
