### ISSUE TITLE
[Bug]: Dashboard gets into panic when affinity selector expressions have no values

### ISSUE THREAD

**Issue by powerfooI** [oceanbase/ob-operator#600]
### Describe the bug

Dashboard gets into panic when affinity selector expressions have no values.

### Environment

Dashboard 0.3.1

### Fast reproduce steps

1. Deploy oceanbase dashboard 0.3.1
2. Apply an OBCluster like with affinity configuration like following,
```yaml
...
  topology:
    - zone: zone1
      replica: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: xxxxxx
                operator: Exists # or DoesNotExist
...
```
3. Open the UI of the dashboard and enter "Cluster" panel
4. The table for OBClusters keeps empty and panics could be found in logs of dashboard
