### ISSUE TITLE
Support Triggering Only One Full Backup

### ISSUE THREAD

**Issue by qchenzi** [oceanbase/ob-operator#656]
### Description

We have a external backup control service that manages and schedules backup tasks. We would like ob-operator to support this flexible backup strategy management approach.

Currently, ob-operator automatically triggers full backups and incremental backups based on the backup strategy at regular intervals. Specifically, we would like ob-operator to trigger only one full backup and then allow the external backup control service to manage the ongoing backup strategies.

**Requirements:**
**Trigger only one full backup**: ob-operator should support triggering a single full backup only, without regularly triggering backup tasks.

**Simplified backup task configuration**: Provide a configuration that allows manually triggering backups.

We appreciate your support in making ob-operator more flexible to accommodate this use case.

**Comment by chris-sun-star** [comment]
I have done some tests on this scenario, and it's actionable
1. create backuppolicy and wait until the preparation is done and the log-archive job and clean job are running successfully.
![image](https://github.com/user-attachments/assets/fca20f3f-92bb-4e06-8143-b842f08b99fe)

2. update the backuppolicy resource to "STOPPED" status, ob-operator will not handle the backuppolicy in this status. You can do this by creating a OBResourceRescue resource.
```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBResourceRescue
metadata:
  namespace: oceanbase
  generateName: backuppolicy-reset-
spec:
  type: reset
  targetKind: OBTenantBackupPolicy
  targetResName: ${backuppolicy-name}
  targetStatus: STOPPED
```
![image](https://github.com/user-attachments/assets/43a5980c-c188-4cef-a5c8-f03c08d41748)

3. create a full backup job manually when needed
```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantBackup
metadata:
  name: backup-full-1
  namespace: oceanbase
spec:
  obClusterName: ${clusterName}
  path: file:///ob-backup/backup/data
  tenantName: ${tenantName}
  tenantSecret: ${secretName}
  type: FULL
```
![image](https://github.com/user-attachments/assets/4b51fd5b-5108-4a77-a9b1-082471a6fcc0)
if you need increment backup, you may just simply change the type to INC
