### ISSUE TITLE
[Question]: Question about NFS as backup option

### ISSUE THREAD

**Issue by mayyyyying** [oceanbase/ob-operator#742]
### Description

Hi there,

I'm trying to use NFS as the obcluster backup option, my settings are as follows

1. In observer & obcluster, I have the backupVolume settings 
```yaml
spec:
  backupVolume:
      volume:
        name: backup
        nfs:
          path: /nfs/obstore
          server: nfs.local
```

2. My obcluster settings:
```yaml
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  annotations:
    oceanbase.oceanbase.com/independent-pvc-lifecycle: "true"
    oceanbase.oceanbase.com/mode: service
    oceanbase.oceanbase.com/single-pvc: "true"
    oceanbase.oceanbase.com/support-static-ip: "true"
  labels:
    app.kubernetes.io/instance: oceanbase-cluster
    app.kubernetes.io/name: oceanbase-cluster
    app.kubernetes.io/version: 4.2.3.1-101000032024061316
    helm.sh/chart: oceanbase-cluster-4.2.3-sp.1-101000032024061316
  name: oceanbase-cluster
  namespace: oceanbase-system
spec:
  backupVolume:
    volume:
      name: backup
      nfs:
        path: /nfs/obstore
        server: nfs.local
  clusterId: 1
  clusterName: obcluster
  observer:
    image: xxxxxxxxxx
    resource:
      cpu: "2"
      memory: 20Gi
    storage:
      dataStorage:
        size: 60Gi
        storageClass: local-path
      logStorage:
        size: 20Gi
        storageClass: local-path
      redoLogStorage:
        size: 60Gi
        storageClass: local-path
  parameters:
  - name: enable_syslog_recycle
    value: "true"
  - name: max_syslog_file_count
    value: "8"
  - name: memory_limit
    value: 18432M
  - name: datafile_maxsize
    value: 57G
  - name: datafile_next
    value: 6G
  scenario: htap
  serviceAccount: default
  topology:
  - nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    replica: 1
    zone: zone1
  userSecrets:
    monitor: ob-user-monitor
    operator: ob-user-operator
    proxyro: ob-user-proxyro
    root: ob-user-root
status:
  image: xxxxxxx
  obzones:
  - status: running
    zone: obcluster-1-zone1
  parameters:
  - name: datafile_next
    value: 6G
  - name: enable_syslog_recycle
    value: "true"
  - name: max_syslog_file_count
    value: "8"
  - name: memory_limit
    value: 18432M
  - name: datafile_maxsize
    value: 57G
  status: running
```

3. Other than the 4 secrets created by obcluster Helm Chart(ob-user-monitor; ob-user-operator; ob-user-proxyro; ob-user-root), I manaully created a t1-ro secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: t1-ro
  namespace: oceanbase-system
data:
  password: WEtMZ1B1aUNnZWVOM2s5Mw==
```

4. OBTenant resource
```yaml
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenant
metadata:
  name: t1
  namespace: oceanbase-system
spec:
  obcluster: oceanbase-cluster
  tenantName: t1
  unitNum: 1
  charset: utf8mb4
  connectWhiteList: '%'
  forceDelete: true
  credentials:
    root: t1-ro
    standbyRo: t1-ro
  pools:
    - zone: zone1
      type:
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 1
        minCPU: 1
        memorySize: 5Gi
        maxIops: 1024
        minIops: 1024
        iopsWeight: 2
        logDiskSize: 12Gi
```

5. Backup Policy resource
```yaml
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantBackupPolicy
metadata:
  name: backup-policy-example
  namespace: qxcp-oceanbase-system
spec:
  obClusterName: "oceanbase-cluster"
  tenantCRName: "t1"
  tenantName: "t1"
  jobKeepWindow: "1d"
  dataClean:
    recoveryWindow: "8d"
  #logArchive:
  #  destination:
  #    type: "NFS"
  #    path: "t1/obstore"
  #  switchPieceInterval: "1d"
  dataBackup:
    destination:
      type: "NFS"
      path: "obstore"
    fullCrontab: "30 0 * * 6"
    incrementalCrontab: "30 1 * * *"
```

The Problem is about this backuppolicy resource, It failed to created on my side with error of
```yaml
Execute sql failed, sql alter system set LOG_ARCHIVE_DEST = ?, param [LOCATION=file:///ob-backup PIECE_SWITCH_INTERVAL=1d BINDING=Optional]: Error 4009 (58030): IO error
```

I'm wondering is there anything I missed in those resources settings? especially settings about NFS. 

Any suggestions would be appreciated, 

Thanks

**Comment by powerfooI** [comment]
Hi there! The `logArchive` part is necessary for oceanbase to run backup progress. You could uncomment the block of `logArchive` and try again. 

By the way, the `[logArchive/dataBackup].destination.path` will be concatenated behind the `file:///ob-backkup` which is mounted as a nfs volume into the pods. The path of `logArchive` should differs from that of `dataBackup`

**Comment by mayyyyying** [comment]
Thanks,

I tried uncomment the logArchive part, got this error still
```yaml
obtenantbackuppolicy-controller  Execute sql failed, sql alter system set LOG_ARCHIVE_DEST = ?, param [LOCATION=file:///ob-backup/obstore1 PIECE_SWITCH_INTERVAL=1d BINDING=Optional]: Error 4009 (58030): IO error
```

settings as follows:

### obcluster pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    ref-obcluster: oceanbase-cluster
    ref-obzone: obcluster-1-zone1
  name: obcluster-1-zone1-fwx6gx
  namespace: oceanbase-system
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: In
            values:
            - ""
  containers:
  - command:
    - bash
    - -c
    - /home/admin/oceanbase/bin/oceanbase-helper start
    env:
    - name: SVC_IP
      value: xx.xx.xx.xx
    - name: EXTRA_OPTION
      value: memory_limit='18432M',datafile_maxsize='57G',datafile_next='6G'
    - name: LD_LIBRARY_PATH
      value: /home/admin/oceanbase/lib
    - name: CPU_COUNT
      value: "16"
    - name: DATAFILE_SIZE
      value: 12G
    - name: LOG_DISK_SIZE
      value: 57G
    - name: CLUSTER_NAME
      value: obcluster
    - name: CLUSTER_ID
      value: "1"
    - name: ZONE_NAME
      value: zone1
    image: xxxxxxxx
    imagePullPolicy: IfNotPresent
    name: observer
    ports:
    - containerPort: 2881
      name: sql
      protocol: TCP
    - containerPort: 2882
      name: rpc
      protocol: TCP
    - containerPort: 8080
      name: info
      protocol: TCP
    readinessProbe:
      failureThreshold: 32
      initialDelaySeconds: 5
      periodSeconds: 2
      successThreshold: 1
      tcpSocket:
        port: 2881
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 20Gi
      requests:
        cpu: "2"
        memory: 20Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/admin/data-file
      name: obcluster-1-zone1-fwx6gx
      subPath: data-file
    - mountPath: /home/admin/data-log
      name: obcluster-1-zone1-fwx6gx
      subPath: data-log
    - mountPath: /home/admin/log
      name: obcluster-1-zone1-fwx6gx
      subPath: log
    - mountPath: /ob-backup
      name: backup
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r7fps
      readOnly: true
    workingDir: /home/admin/oceanbase
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: master0
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: obcluster-1-zone1-fwx6gx
    persistentVolumeClaim:
      claimName: obcluster-1-zone1-fwx6gx
  - name: backup
    nfs:
      path: /nfs/obstore
      server: nfs.local
  - name: kube-api-access-r7fps
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

### obtenantbackuppolicy
```yaml
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantBackupPolicy
metadata:
  name: backup-policy-example
  namespace: oceanbase-system
spec:
  obClusterName: "oceanbase-cluster"
  tenantCRName: "t1"
  tenantName: "t1"
  jobKeepWindow: "1d"
  dataClean:
    recoveryWindow: "8d"
  logArchive:
    destination:
      type: "NFS"
      path: "obstore1"
    switchPieceInterval: "1d"
  dataBackup:
    destination:
      type: "NFS"
      path: "obstore2"
    fullCrontab: "30 0 * * 6"
    incrementalCrontab: "30 1 * * *"
```

This is exec into obcluster pod file directory.
<img width="586" alt="Image" src="https://github.com/user-attachments/assets/42a05ed9-349a-4f13-8843-5df41378f5d5" />

Is there any other possibilities that I may missing among the above settings?

Thanks
