### ISSUE TITLE
[Question]: Connect Refuse :2881

### ISSUE THREAD

**Issue by Menniti** [oceanbase/ob-operator#798]
### Description

Hello guys,
I`m facing a issue, using operator in k8s

For some reason seems to cluster not be available when it start up

```
  Warning  Unhealthy  2m23s (x19 over 2m57s)  kubelet            Readiness probe failed: dial tcp 10.244.0.6:2881: connect: connection refused
```

my current code

```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: oceanbase-cluster
  namespace: oceanbase
  # annotations:
  #   "oceanbase.oceanbase.com/independent-pvc-lifecycle": "standalone" 
    # "oceanbase.oceanbase.com/mode": "standalone" or "service"
    # "oceanbase.oceanbase.com/single-pvc": "true" 
spec:
  clusterName: obcluster
  clusterId: 1
  serviceAccount: "default"
  userSecrets:
    root: root-password
  topology:
    - zone: zone1
      replica: 1
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          operator: "Exists"
          effect: "NoSchedule"
      # nodeSelector:
      #   k1: v1
      # affinity:
      #   nodeAffinity:
      #   podAffinity:
      #   podAntiAffinity:
      # tolerations:
      #   - key: "obtopo"
      #     value: "zone"
      #     effect: "NoSchedule"
    # - zone: zone2
    #   replica: 1
    # - zone: zone3
    #   replica: 1
  observer:
    image: oceanbase/oceanbase-cloud-native:4.2.1.6-106000012024042515
    resource:
      cpu: 2
      memory: 16Gi
    storage:
      dataStorage:
        storageClass: juicefs-sc
        size: 100Gi
      redoLogStorage:
        storageClass: juicefs-sc
        size: 100Gi
      logStorage:
        storageClass: juicefs-sc
        size: 30Gi

  monitor:
    image: oceanbase/obagent:4.2.0-100000062023080210
    resource:
      cpu: 1
      memory: 1Gi

  parameters:
    - name: system_memory
      value: 2G
    - name: "__min_full_resource_pool_memory"
      value: "2147483648" # 2G
  # backupVolume:
  #   volume:
  #     name: backup
  #     nfs:
  #       server: 1.1.1.1
  #       path: /opt/nfs
  #       readOnly: false

```

does anyone knows why it cannot connect ? I would like to have a cluster on this

**Comment by Menniti** [comment]
I also have attempt this
```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: test
  namespace: oceanbase
spec:
  clusterName: obcluster
  clusterId: 1
  serviceAccount: "default"
  userSecrets:
    root: root-password
    proxyro: proxyro-password
    monitor: monitor-password
    operator: operator-password
  topology:
    - zone: zone1
      replica: 1
  observer:
    image: oceanbase/oceanbase-cloud-native:4.2.1.6-106000012024042515
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: juicefs-sc
        size: 30Gi
      redoLogStorage:
        storageClass: juicefs-sc
        size: 30Gi
      logStorage:
        storageClass: juicefs-sc
        size: 20Gi
  parameters:
  - name: system_memory
    value: 1G
  - name: "__min_full_resource_pool_memory"
    value: "2147483648" # 2G
```
and seems to be the same problem
