### ISSUE TITLE
[Question]: The information of the deleted pod still remains in the cluster.

### ISSUE THREAD

**Issue by uroot666** [oceanbase/ob-operator#84]
### Description
imager version: oceanbasedev/ob-operator:1.2.0
```
apiVersion: cloud.oceanbase.com/v1
kind: OBCluster
metadata:
  name: ob-test
  namespace: test
spec:
  imageRepo: oceanbasedev/oceanbase-cn
  tag: v4.1.0.0-100000192023032010
  imageObagent: oceanbase/obagent:1.2.0
  clusterID: 1
  topology:
    - cluster: cn
      zone:
      - name: zone1
        region: region1
        nodeSelector:
          ob.zone: zone1
        replicas: 3
      parameters:
        - name: log_disk_size
          value: "24G"
        - name: system_memory
          value: "1G"
        - name: memory_limit
          value: "9G"
  resources:
    cpu: 4
    memory: 10Gi
    storage:
      - name: data-file
        storageClassName: "local-path"
        size: 50Gi
      - name: data-log
        storageClassName: "local-path"
        size: 50Gi
      - name: log
        storageClassName: "local-path"
        size: 30Gi
      - name: obagent-conf-file
        storageClassName: "local-path"
        size: 1Gi
```

when testing ob-operator, it was observed that after deleting a pod, it still appears in the cluster information and is displayed as 'INACTIVE' status. The operator continues to perform health checks. Is this considered normal? In a scenario with three zones, each having one node, removing a node from one zone can recover normally. However, when attempting to delete nodes from other zones, new pods fail to start properly.
![image](https://github.com/oceanbase/ob-operator/assets/18516722/42d6b78e-4f3a-45a6-aa2f-e5ec79ebe31f)
![image](https://github.com/oceanbase/ob-operator/assets/18516722/c97f367a-d282-452c-ab26-90ab96e9ab63)
